git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 --diff-so-fancy --pager bat
gui:
  sidePanelWidth: 0.2
  expandFocusedSidePanel: true
  skipDiscardChangeWarning: true
  mainPanelSplitMode: 'flexible'
  nerdFontsVersion: '3'
  showBranchCommitHash: true
  # showDivergenceFromBaseBranch: 'arrowAndNumber'
